[2025-06-05T14:36:36.397-0400] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: netflix_retention_dag.generate_mock_data manual__2025-06-05T18:36:34.986866+00:00 [queued]>
[2025-06-05T14:36:36.399-0400] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: netflix_retention_dag.generate_mock_data manual__2025-06-05T18:36:34.986866+00:00 [queued]>
[2025-06-05T14:36:36.399-0400] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-05T14:36:36.403-0400] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): generate_mock_data> on 2025-06-05 18:36:34.986866+00:00
[2025-06-05T14:36:36.405-0400] {standard_task_runner.py:60} INFO - Started process 59862 to run task
[2025-06-05T14:36:36.408-0400] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'netflix_retention_dag', 'generate_mock_data', 'manual__2025-06-05T18:36:34.986866+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/netflix_retention_dag.py', '--cfg-path', '/var/folders/h9/p5fdhb7n7s964d6sg7dxh0rw0000gn/T/tmpf2t0nljf']
[2025-06-05T14:36:36.411-0400] {standard_task_runner.py:88} INFO - Job 9: Subtask generate_mock_data
[2025-06-05T14:36:36.425-0400] {task_command.py:423} INFO - Running <TaskInstance: netflix_retention_dag.generate_mock_data manual__2025-06-05T18:36:34.986866+00:00 [running]> on host mac.lan1
[2025-06-05T14:36:36.445-0400] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='netflix_retention_dag' AIRFLOW_CTX_TASK_ID='generate_mock_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-05T18:36:34.986866+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-05T18:36:34.986866+00:00'
[2025-06-05T14:36:36.446-0400] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/h9/p5fdhb7n7s964d6sg7dxh0rw0000gn/T
[2025-06-05T14:36:36.446-0400] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /Users/vionasanda/Projects/netflix-retention-project/etl/generate_data.py']
[2025-06-05T14:36:36.449-0400] {subprocess.py:86} INFO - Output:
[2025-06-05T14:36:36.856-0400] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-06-05T14:36:36.857-0400] {subprocess.py:93} INFO -   File "/Users/vionasanda/Projects/netflix-retention-project/etl/generate_data.py", line 31, in <module>
[2025-06-05T14:36:36.857-0400] {subprocess.py:93} INFO -     users_df.to_csv("data/raw/users.csv", index=False)
[2025-06-05T14:36:36.857-0400] {subprocess.py:93} INFO -   File "/Users/vionasanda/Projects/netflix-retention-project/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
[2025-06-05T14:36:36.857-0400] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-06-05T14:36:36.857-0400] {subprocess.py:93} INFO -   File "/Users/vionasanda/Projects/netflix-retention-project/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3967, in to_csv
[2025-06-05T14:36:36.858-0400] {subprocess.py:93} INFO -     return DataFrameRenderer(formatter).to_csv(
[2025-06-05T14:36:36.858-0400] {subprocess.py:93} INFO -   File "/Users/vionasanda/Projects/netflix-retention-project/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
[2025-06-05T14:36:36.858-0400] {subprocess.py:93} INFO -     csv_formatter.save()
[2025-06-05T14:36:36.858-0400] {subprocess.py:93} INFO -   File "/Users/vionasanda/Projects/netflix-retention-project/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 251, in save
[2025-06-05T14:36:36.859-0400] {subprocess.py:93} INFO -     with get_handle(
[2025-06-05T14:36:36.859-0400] {subprocess.py:93} INFO -   File "/Users/vionasanda/Projects/netflix-retention-project/venv/lib/python3.9/site-packages/pandas/io/common.py", line 749, in get_handle
[2025-06-05T14:36:36.859-0400] {subprocess.py:93} INFO -     check_parent_directory(str(handle))
[2025-06-05T14:36:36.859-0400] {subprocess.py:93} INFO -   File "/Users/vionasanda/Projects/netflix-retention-project/venv/lib/python3.9/site-packages/pandas/io/common.py", line 616, in check_parent_directory
[2025-06-05T14:36:36.859-0400] {subprocess.py:93} INFO -     raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
[2025-06-05T14:36:36.859-0400] {subprocess.py:93} INFO - OSError: Cannot save file into a non-existent directory: 'data/raw'
[2025-06-05T14:36:36.881-0400] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-05T14:36:36.885-0400] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/vionasanda/Projects/netflix-retention-project/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/vionasanda/Projects/netflix-retention-project/venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-05T14:36:36.893-0400] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=netflix_retention_dag, task_id=generate_mock_data, execution_date=20250605T183634, start_date=20250605T183636, end_date=20250605T183636
[2025-06-05T14:36:36.896-0400] {standard_task_runner.py:107} ERROR - Failed to execute job 9 for task generate_mock_data (Bash command failed. The command returned a non-zero exit code 1.; 59862)
[2025-06-05T14:36:36.915-0400] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-05T14:36:36.922-0400] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
